### PR TITLE
Update sfml to 2.5.1 and csfml to 2.5

### PR DESCRIPTION
**Pull request by ptriller**
I Updated Swig to 4.0.1 and changed the way the local compile works a little bit

I updated sfm to 2.5.1 and csfml to 2.5. Since I was doing the Building on Ubuntu/Linux I did not use the local compile script but used the install libcsfml-dev and libsfml-dev packages from Ubuntu

In the "Windows.i" is a %rename type evType because I didn't like the automatic rename swig did to "Xtype"

I am not very knowledgeable about sfml so I only ran some limited tests.

### CODE REVIEW

**Comment by matjam** [comment]
@teh-cmc seems like a quality repo. 

If you don't want to maintain it anymore maybe add @ptriller to the list of people who can merge PRs. I'd like to tinker with this package.

**Comment by bartekpacia** [comment]
please, don't let this project die

**Comment by TheFern2** [comment]
> please, don't let this project die

Fair to say this project has been abandon, two years without maintainer reply... @ptriller have you started another repo, not a fork?

**Comment by Telroshan** [comment]
Hello, just picked up the ownership of this repo. I'm closing this pull request since there are lots of conflicts now _(I had initially forked it as well)_, please note some of your changes are in there though _(the ignores to fix the annoying deprecation warnings, the evType renaming)_
Master now is up to date with SFML 2.5.1 and CSFML 2.5.1 !

**Comment by bartekpacia** [comment]
Congrats and thank you for being a maintainer!

**Comment by matjam** [comment]
You rock! Thanks for picking up the project!

**Pull request closed without merging**
